# Generated by Django 4.1 on 2023-05-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("self_number", models.IntegerField()),
                ("name", models.CharField(max_length=30)),
                ("school", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=30, unique=True)),
                ("email", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=30)),
            ],
        ),
    ]
