# Generated by Django 4.1 on 2023-05-29 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "学生", "verbose_name_plural": "学生"},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={"verbose_name": "教师", "verbose_name_plural": "教师"},
        ),
    ]
