# Generated by Django 4.1 on 2023-05-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_rename_exam_number_student_self_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="phone",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
