# Generated by Django 4.1 on 2023-05-29 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exam", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamScore",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("score", models.IntegerField()),
                (
                    "exam_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exam.exam",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.student",
                    ),
                ),
                (
                    "teacher_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnswerRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_right", models.BooleanField()),
                (
                    "exam",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exam.exam",
                    ),
                ),
                (
                    "question_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exam.question",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.student",
                    ),
                ),
            ],
        ),
    ]
