# Generated by Django 4.1 on 2023-05-29 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answerrecord",
            options={"verbose_name": "答题情况", "verbose_name_plural": "答题情况"},
        ),
        migrations.AlterModelOptions(
            name="examscore",
            options={"verbose_name": "考试成绩", "verbose_name_plural": "考试成绩"},
        ),
    ]
