# Generated by Django 4.1 on 2023-05-24 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0002_alter_exam_paper_alter_examorder_exam_and_more"),
        ("user", "0003_alter_student_phone_alter_teacher_phone"),
        ("marking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerrecord",
            name="exam",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="exam.exam"
            ),
        ),
        migrations.AlterField(
            model_name="answerrecord",
            name="question_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="exam.question",
            ),
        ),
        migrations.AlterField(
            model_name="answerrecord",
            name="student_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.student",
            ),
        ),
        migrations.AlterField(
            model_name="examscore",
            name="exam_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="exam.exam"
            ),
        ),
        migrations.AlterField(
            model_name="examscore",
            name="student_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.student",
            ),
        ),
        migrations.AlterField(
            model_name="examscore",
            name="teacher_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.teacher",
            ),
        ),
    ]
