# Generated by Django 4.1 on 2023-05-29 10:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("date", models.DateField()),
                ("start_time", models.TimeField(default=datetime.time(0, 0))),
                ("end_time", models.TimeField(default=datetime.time(0, 0))),
                ("place", models.CharField(max_length=30)),
                ("is_online", models.BooleanField()),
                ("is_beginning", models.BooleanField()),
                ("max_students", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question_ids", models.CharField(max_length=512)),
                ("type", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.IntegerField()),
                ("question", models.CharField(max_length=100)),
                ("answer", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ExamOrder",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("paid", models.BooleanField()),
                ("payment", models.FloatField()),
                ("pay_time", models.DateField(default=django.utils.timezone.now)),
                (
                    "exam",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exam.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exam",
            name="paper",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="exam.paper"
            ),
        ),
    ]
