# Generated by Django 4.1 on 2023-05-24 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_student_phone_alter_teacher_phone"),
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="paper",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="exam.paper"
            ),
        ),
        migrations.AlterField(
            model_name="examorder",
            name="exam",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="exam.exam"
            ),
        ),
        migrations.AlterField(
            model_name="examorder",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.student",
            ),
        ),
    ]
