# Generated by Django 4.1 on 2023-05-29 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exam",
            options={"verbose_name": "考试安排", "verbose_name_plural": "考试安排"},
        ),
        migrations.AlterModelOptions(
            name="examorder",
            options={"verbose_name": "订单记录", "verbose_name_plural": "订单记录"},
        ),
        migrations.AlterModelOptions(
            name="paper",
            options={"verbose_name": "试卷", "verbose_name_plural": "试卷"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "题目", "verbose_name_plural": "题目"},
        ),
    ]
